### ISSUE TITLE
fill and fontface otions for geom_gene_label

### ISSUE THREAD

**Issue by code-acc** [thackl/gggenomes#141]
Hello!

I want to color gene labels with the same colors as geom_gene (I have "geom_gene(aes(label=gene))"). Also, I want gene labels in italics. 
fill and fontface are not working for geom_gene_label. Can you please recommend a way?

Thank you,
Minal

**Comment by thackl** [comment]
This works for me. If you mean something else, please provide an example.

```
g0 <- tibble(seq_id="a", start=10, end=500, gene="foo")
gggenomes(g0) +
  geom_gene(aes(fill=gene)) +
  geom_gene_label(aes(label=gene, color=gene), fontface="italic", show.legend=FALSE)
```

![image](https://user-images.githubusercontent.com/9363087/216629142-a5d77bab-1e51-4e1e-93be-15141911566b.png)

**Comment by minal033** [comment]
Yes, that worked! Thank you so much! Now encountering a different problem though. Some of the genes are pseudogenes so I use greek psi symbol to label them. Before color and fontface, plot was showing psi symbol but now it shows some strange character instead of psi. I tried a couple of online solutions to convert encoding into UTF-8 but no success yet. Please let me know if you have a solution that can work. Here is a screenshot of the table that I read in R:
![image](https://user-images.githubusercontent.com/35659975/216690304-c18c0a13-3aa8-4ba1-b6bf-5f2d2f8b2460.png)

**Comment by thackl** [comment]
Hm, strange. I cannot reproduce this on my system, see below.
```
# thought this would work with `parse=T` but got no character for psi at all
g0 <- tibble(
  seq_id="a", start=c(10, 600), end=c(500, 1000),
  # this seems to work just fine
  gene=c("foo", "ψ"),
  # thought this would work with `parse=T` 
  # but got no character for psi at all
  gene_parse=c("foo", "psi"),
  # unicode seems to work as well
  gene_unicode=gsub("ψ", "\u03C8", gene)
)

gggenomes(g0) +
  geom_gene(aes(fill=gene)) +
  # psi and italic
  geom_gene_label(aes(label=gene, color=gene), 
                  fontface="italic", show.legend=F, nudge_x=-100) +
  # no psi, and not italic
  geom_gene_label(aes(label=gene_parse, color=gene), 
                  fontface="italic", show.legend=F, parse=T) +
  # psi and italic
  geom_gene_label(aes(label=gene_unicode, color=gene),
                  fontface="italic", show.legend=F, nudge_x=100)
```
![image](https://user-images.githubusercontent.com/9363087/216710729-fa1e13c0-21c6-4488-921d-6f8e3b0f812f.png)

**Comment by code-acc** [comment]
Thank you for trying this! Your solution works for me but only when I write a tibble. In my case, I have to read a table. I found out that if I save the file with .txt, and read with read.delim(), then psi is labeled as a greek letter on the plot. Other extensions like .tsv, .csv, .xlsx don't work!
