### ISSUE TITLE
Last gggenomes example failed with mysterious error

### ISSUE THREAD

**Issue by thackl** [thackl/gggenomes#43]
https://thackl.github.io/gggenomes/reference/gggenomes.html

After reading the second file apparently successful, it just says "Error:" but without any error message...

**Comment by iimog** [comment]
This is strange. I don't know why this happens. When I build locally it works (with some warnings). Not sure if warnings are treated as errors in this context but I don't think so.
![local_build](https://user-images.githubusercontent.com/7403236/108319850-4a5af080-71c2-11eb-80c1-a1263b343030.png)

**Comment by thackl** [comment]
It seems to be an issue with `read_gff`. Same happens here https://thackl.github.io/gggenomes/reference/read_tracks.html. There are no warnings, though, from `read_gff` on local builds. The `read_paf` warnings are unrelated, I think.

Why `read_gff` fails on CI build, I don't have a clue...

**Comment by iimog** [comment]
Okay, looking into it a bit more. Debugging GitHub actions is not straightforward. This looks promising but does not work because I get denied errors from rstudio cdn: https://github.com/nektos/act
This also might be an idea but is rather hacky: https://dev.to/retyui/how-debugging-github-actions-with-ssh-273n
So my suggestion would be to upgrade `R` in the action from `4.0.0` to `4.0.4` to see if some bug that has since been fixed causes this error.

**Comment by thackl** [comment]
Sound like a good plan to me.

**Comment by thackl** [comment]
Actual problem is a bug in `across()` dplyr-1.0.4 https://github.com/tidyverse/dplyr/pull/5765. dplyr-1.0.4-dev works. Fixed dplyr-1.0.5 about to be released.
