### ISSUE TITLE
Easyfig or mauve outputs?

### ISSUE THREAD

**Issue by cms72** [thackl/gggenomes#82]
Hi! Is there a way to incorporate outputs from Easyfig and Mauve? Thanks!

**Comment by thackl** [comment]
Not yet, but both are on my mental list of things that would be nice to have. Do you have some example data that you'd want to visualize? That might help me implementing such features faster!

**Comment by cms72** [comment]
Hi! Thanks for the reply. I do! I'm looking at pathogenicity islands (there are 24) - and was looking to compare them. 

[Archive.zip](https://github.com/thackl/gggenomes/files/7167442/Archive.zip)

Here's what I've done so far:
![image](https://user-images.githubusercontent.com/29542861/133383941-8de04671-3e8e-458d-b640-aaf0a5ab9540.png)

**Comment by thackl** [comment]
Great, thanks for sharing. My understanding of the easyfig output is that it is essentially just an output form all-vs-all nucleotide blast comparisons. That is very easy to import into gggenomes. Note, though, that for the two example sequences you sent, there is barely any significant similarity between the sequence on nucleotide level, so the visualization, although working, is not too informative.

```
library(tidyverse)
library(gggenomes)

# NOTE: had to remove the "()" from the filenames for this to work
s0 <- read_seqs(list.files(pattern="*.gb"))
g0 <- read_feats(list.files(pattern="*.gb"))

# this is just blastn --outfmt 6
e0 <- read_links("12.easyfig.out", format="blast")
# need to match ids - easyfig uses filename instead of the seq_id
e0$seq_id <- s0$seq_id[1]
e0$seq_id2 <- s0$seq_id[2]

gggenomes(g0, s0, links=e0) +
  geom_seq() + geom_gene() +
  geom_link()
```
![82-1](https://user-images.githubusercontent.com/9363087/133396555-4d350d6b-f50b-4999-9135-3bc10e0e66d1.png)

At least for this case with remotely related elements, you get better insights from protein-level comparisons. Those are also quite easy to visualize in gggenomes.

```
# all-vs-all protein blast
# blastp -query SPI-1_NC_003198_.faa -subject SPI-2_NC_003198_.faa -outfmt 6 -evalue 1e-5 > spi.o6
b0 <- read_sublinks("spi.o6") # sublinks - links connecting features, such as genes, not contigs directly
# overwrite default feat_id parsed from locus_tag with protein_id, which is used
# in protein.faa
g1 <- g0 %>% mutate(feat_id = protein_id) 

gggenomes(g1, s0) %>%
  add_sublinks(blast=b0) +
  geom_seq() + geom_gene() + geom_link()
```
![82-2](https://user-images.githubusercontent.com/9363087/133396800-8f1b3a17-cd8b-4beb-b36a-dfa172573ef4.png)

For larger datasets, I'd alternatively consider doing/visualizing protein clusters instead of just blast hits. Could be done like so
```
# mmseqs easy-cluster *.faa spi /tmp -e 1e-5 -c 0.7
c0 <- read_tsv("spi_cluster.tsv", col_names=c("cluster_id", "feat_id"))
c1 <- c0 %>% add_count(cluster_id) %>% filter(n>1) # remove singletons

gggenomes(g1, s0) %>%
  add_sublinks(blast=b0) %>%
  add_clusters(mmseqs=c1) +
  geom_seq() +
  geom_gene(aes(fill=cluster_id)) + # color genes by clusters
  geom_link() + # blast links
  # clusters can also be shown as links (overlaying on blast here)
  geom_link(aes(color=cluster_id), data=links(mmseqs), fill=NA)
```
![82-3](https://user-images.githubusercontent.com/9363087/133397012-e39c988d-f143-4cdc-8487-b4879b560b90.png)

There is also quite a few options for further manipulating your plot - flipping sequences, zooming in etc - that make more sense on larger data set. Happy to talk more if you want to explore this further, also directly via email if that would make it easier for you to share data.

**Comment by cms72** [comment]
Hi! This looks really great! Thank you!! I will try it out! Would it be the same for mauve outputs (see below)?

[Archive.zip](https://github.com/thackl/gggenomes/files/7188882/Archive.zip)

**Comment by thackl** [comment]
Mauve output is a bit more complex. And it depends on what parts of it you are interested / how similar to Mauve's Viewer output you want the result. Below is some simple code that produces a gggenomes plot from mauve output - but it's just quick and dirty with minimal information. As said in the beginning, for better code it depends a bit on how you envision the plot to look like and what information you want it to convey. I'd be curious about your thoughts!

FYI,  I took a different example (3 bacterial genomes) because your sequences share so little similarity at nucleotide level that the plot looked strange even in Mauve ;)

**Mauve**
![image](https://user-images.githubusercontent.com/9363087/134076658-15912d75-e854-4447-8c48-1d960188d483.png)
**gggenomes**
![image](https://user-images.githubusercontent.com/9363087/134078010-40ee371e-8703-49b3-bbd4-a2c9cea1a27c.png)

```
library(tidyverse)
library(gggenomes)

# convert Mauve main output file in a parsible table with some perl magic
# perl -ane 'BEGIN{$i=1; print "seq_id\tstart\tend\tstrand\tfeat_id\tcluster_id\n"} $i++ if /^=/; if(/^>\s?(\d+):(\d+)-(\d+)\s(.)/){print "s$1\t$2\t$3\t$4\tf$1-$i\tc$i\n"}' mauve-out > mauve-out.tsv

# read blocks as features
mauve_blocks <- read_tsv("mauve-pro/hl.tsv") %>%
  add_count(cluster_id) %>%
  mutate(cluster_id = ifelse(n>1, cluster_id, NA))

# blocks are clustered - easiest way to add links
mauve_clusters <- select(s1, cluster_id, feat_id) %>%
  drop_na()

gggenomes(feats=mauve_blocks) %>%
  add_clusters(mauve_clusters, .track_id = feats) +
  geom_feat(aes(color=cluster_id), position="strand") +
  geom_link(aes(fill=cluster_id))
```

**Comment by cms72** [comment]
Wow. Thank you! I'll give it a try and ill let you know how I go :)
